[package]
name = "nitoritag"
version = "0.1.0"
authors = ["fence <fence@desu-mail.moe>"]

[dependencies]
gdk = ""
glib= ""
id3 = "0.6.2"
metaflac = "0.2.4"
taglib = "1.0.0"
url = "2.2.1"
gtk = { version="0.8", features=["v3_20"] }
